---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.4.2
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

<!-- #region nbgrader={"grade": false, "grade_id": "h00", "locked": true, "schema_version": 3, "solution": false} -->
Osnabrück University - Computer Vision (Winter Term 2019/20) - Prof. Dr.-Ing. G. Heidemann, Ulf Krumnack, Axel Schaffland
<!-- #endregion -->

<!-- #region nbgrader={"grade": false, "grade_id": "h01", "locked": true, "schema_version": 3, "solution": false} -->
# Exercise Sheet 00: Preparation
<!-- #endregion -->

<!-- #region nbgrader={"grade": false, "grade_id": "h02", "locked": true, "schema_version": 3, "solution": false} -->
## Introduction

This is an introductory exercise sheet that shall help you getting started with Python and Jupyter Notebooks, the tools we will use in the practice sessions of the Computer Vision course. The is a preparatory sheet and you are not require to submit your solutions.

We encourage you to work through this sheet to make sure you get familiar with this setup and to check if you feel comfortable with reading and understanding the documentation of the software packages.

In case of questions, feel free to post them to the forum and/or raise them in the next practice session.
<!-- #endregion -->

<!-- #region nbgrader={"grade": false, "grade_id": "ex-setup3", "locked": true, "schema_version": 3, "solution": false} -->
## Assignment 0: Check your installation
Check that your installation succeeded and all required packages are available by executing the following cell (type <kbd>Ctrl</kbd>+<kbd>&#x23ce;</kbd>, on German keyboards <kbd>Strg</kbd>+<kbd>&#x23ce;</kbd>, or press the "run cell"-button at the toolbar above). Seeing no output (no complains) means that your environment seems fine:
<!-- #endregion -->

```{python}
import importlib
assert importlib.util.find_spec('numpy') is not None , 'numpy not found'
assert importlib.util.find_spec('matplotlib') is not None, 'matplotlib not found'
assert importlib.util.find_spec('imageio') is not None , 'imageio not found'
assert importlib.util.find_spec('scipy') is not None , 'scipy not found'
```

<!-- #region nbgrader={"grade": false, "grade_id": "ex-setup-remarks", "locked": true, "schema_version": 3, "solution": false} -->
## Remarks:

* If you experience any troubles, ask your fellow students or send us an e-mail - we are always happy to help.
* If you do not want to use Python to do the exercises, but prefer another programming language, you may ask the tutors if they are willing to support it. However, the practice sessions will focus on Python and will probably not cover other languages.
<!-- #endregion -->

<!-- #region nbgrader={"grade": false, "grade_id": "cell-e2b9ea6540929a58", "locked": true, "schema_version": 3, "solution": false} -->
## Assignment 1: Image I/O

`imageio` is a Python library that provides an easy interface to read and write a wide range of image data. The goal of this exercise is to get familiar with different ways of obtaining images for further processing.
<!-- #endregion -->

<!-- #region nbgrader={"grade": false, "grade_id": "cell-dfb47c896b16d37b", "locked": true, "schema_version": 3, "solution": false} -->
**a) Example images:** `imageio` provides a number of example images, which can be loaded by the special URI `imageio:`. These include classic 2D images, as well as animated and volumetric images. 

Find out what other images are provided and how these are represented when loaded as numpy array.
<!-- #endregion -->

```{python nbgrader={'grade': True, 'grade_id': 'cell-4c4e189c29e97763', 'locked': False, 'points': 1, 'schema_version': 3, 'solution': True}}
# %matplotlib inline
import matplotlib.pyplot as plt
import imageio

filename = 'chelsea.png'

### BEGIN SOLUTION
# The imageio documenation lists in section "2.5 Imageio standard images"
# the available images:
#filename = 'chelsea.bsdf'  # The chelsea.png in a BSDF file(for testing)
#filename =  'newtonscradle.gif' # Animated GIF of a newton’s cradle
#filename =  'cockatoo.mp4'  # Video file of a cockatoo
#filename =  'stent.npz'  # Volumetric image showing a stented abdominal aorta
#filename =  'astronaut.png'  # Image of the astronaut Eileen Collins
#filename =  'camera.png'  # Classic grayscale image of a photographer
#filename =  'checkerboard.png'  # Black and white image of a chekerboard
#filename =  'chelsea.png'  # Image of Stefan’s cat
#filename =  'clock.png'  # Photo of a clock with motion blur (Stefan van der Walt)
#filename =  'coffee.png'  # Image of a cup of coffee (Rachel Michetti)
#filename =  'coins.png'  # Image showing greek coins from Pompeii
#filename =  'horse.png'  # Image showing the silhouette of a horse (Andreas Preuss)
#filename =  'hubble_deep_field.png'  # Photograph taken by Hubble telescope (NASA)
#filename =  'immunohistochemistry.png' # Immunohistochemical (IHC) staining
#filename =  'moon.png'  # Image showing a portion of the surface of the moon
#filename =  'page.png'  # A scanned page of text
#filename =  'text.png'  # A photograph of handdrawn text
#filename =  'wikkie.png'  # Image of Almar’s cat
#filename =  'chelsea.zip'  # The chelsea.png in a zipfile (for testing)
# this list is also available at
# https://imageio.readthedocs.io/en/stable/standardimages.html
### END SOLUTION

im =  imageio.imread('imageio:' + filename)

plt.figure()
plt.title(f"{filename}: {im.shape}")
plt.imshow(im)
plt.show()
```

<!-- #region nbgrader={"grade": false, "grade_id": "cell-0dfa25076996bb59", "locked": true, "schema_version": 3, "solution": false} -->
**(b) Loading an image from a file**. Usually, you will have to load images from a file. We have uploaded an example image to the StudIP folder along with this exercise sheet. Load that image using the `imageio` library.
<!-- #endregion -->

```{python nbgrader={'grade': True, 'grade_id': 'cell-b9de9ac530ecf609', 'locked': False, 'points': 1, 'schema_version': 3, 'solution': True}}
# %matplotlib inline
import matplotlib.pyplot as plt

### BEGIN SOLUTION
import imageio

#im = imageio.imread("cow.jpg")
im = imageio.imread("colourImage.jpg")
### END SOLUTION

plt.figure()
plt.title(f"Image: {im.shape}")
plt.imshow(im)
plt.show()
```

<!-- #region nbgrader={"grade": false, "grade_id": "cell-d55e25d7535d0978", "locked": true, "schema_version": 3, "solution": false} -->
**(c) Download an image from the web**. `imageio` also allows to load images from arbitrary URLs. Download an image from a URL of your choice and display it.
<!-- #endregion -->

```{python nbgrader={'grade': True, 'grade_id': 'cell-5be8094ec03ecc4e', 'locked': False, 'points': 1, 'schema_version': 3, 'solution': True}}
# %matplotlib inline
import matplotlib.pyplot as plt
import imageio

### BEGIN SOLUTION
im = imageio.imread("https://github.com/imageio/imageio-binaries/raw/master/images/camera.png")

plt.figure()
plt.title(f"Image: {im.shape}")
plt.imshow(im)
plt.show()
### END SOLUTION
```

<!-- #region nbgrader={"grade": false, "grade_id": "cell-8486e2482bc8265b", "locked": true, "schema_version": 3, "solution": false} -->
**(d) Storing image as file.** The function `imageio.imsave()` can be used to store images on your harddrive. Mark the head of the cameraman with a rectangle and store the resulting image in a file. Check the saved image with some external program.
<!-- #endregion -->

```{python nbgrader={'grade': True, 'grade_id': 'cell-b38e5d41512dc3c2', 'locked': False, 'points': 2, 'schema_version': 3, 'solution': True}}
# %matplotlib inline
import matplotlib.pyplot as plt
import imageio

im =  imageio.imread('imageio:camera.png')

### BEGIN SOLUTION
x1, x2 = 190,270
y1, y2 = 70,160
box = 255
im[(y1,y2),x1:x2] = box
im[y1:y2,(x1,x2)] = box

imageio.imsave('example.png', im)
### END SOLUTION

plt.figure(figsize=(12,12))
plt.title(f"Image: {im.shape}")
plt.imshow(im)
plt.show()
```

<!-- #region nbgrader={"grade": false, "grade_id": "cell-92a05cbfd7ea0add", "locked": true, "schema_version": 3, "solution": false, "task": false} -->
**(e) Acquire image from webcam (bonus)** `imageio` also allows to acquire images from a webcam. However, accessing the webcam relies on external software and requires that your operating system grants access to the webcam. Try to make the following cell work!
<!-- #endregion -->

```{python}
# %matplotlib inline
import matplotlib.pyplot as plt
import imageio

reader = imageio.get_reader('<video0>')
im = reader.get_next_data()

plt.figure()
plt.title(f"Webcam image: {im.shape}")
plt.imshow(im)
plt.show()
```

<!-- #region nbgrader={"grade": false, "grade_id": "cell-38b7f34be3403b53", "locked": true, "schema_version": 3, "solution": false} -->
## Assignment 2: Displaying images
In exercises and during the practice sessions, we will make extensive use of `matplotlib`'s `imshow` function for displaying images. Properly understanding the details of how this function works is essential to avoid problems later on. Take a close look at the documentation and then answer the following questions:
<!-- #endregion -->

<!-- #region nbgrader={"grade": false, "grade_id": "cell-75af10dfb6197e3d", "locked": true, "schema_version": 3, "solution": false, "task": false} -->
**(a) Origin:** The default behaviour of `imshow` is to display the origin (the point with coordinates (0,0)) at the upper left corner. How can you change this to the lower left corner (as it is usually done in mathematical contexts when displaying graphs)?
<!-- #endregion -->

```{python nbgrader={'grade': True, 'grade_id': 'cell-859fbd418004678f', 'locked': False, 'points': 1, 'schema_version': 3, 'solution': True, 'task': False}}
# %matplotlib inline
import matplotlib.pyplot as plt
import imageio

im = imageio.imread("imageio:camera.png")

plt.figure()
plt.title(f"shape: {im.shape}")
### BEGIN SOLUTION
plt.imshow(im, origin='lower')
### END SOLUTION
plt.show()
```

<!-- #region nbgrader={"grade": false, "grade_id": "cell-213eeac484b06e9c", "locked": true, "schema_version": 3, "solution": false} -->
**(b) Monochrome images:** When displaying monochrome images (that is 2-dimensional arrays), they will by default not be displayed as grayscale by `imshow` but rather appear yellow-greenish. Explain why this is the case and how you can achieve  grayscale output.
<!-- #endregion -->

<!-- #region nbgrader={"grade": true, "grade_id": "cell-2fc0ab8469dd504b", "locked": false, "points": 0.5, "schema_version": 3, "solution": true} -->
Matplotlib displays monochrome images using a colormap (see [Matplotlib documentation: colormaps](https://matplotlib.org/gallery/color/colormap_reference.html)), mapping values present in the image to the colors of the colormap. The default colormap (`plt.rcParams['image.cmap']`) is `'viridis'`. To obtain a gray scale image, you have to use the colormap `'gray'`. There are different ways to achieve this.
<!-- #endregion -->

```{python nbgrader={'grade': True, 'grade_id': 'cell-22b8021c9ab6b152', 'locked': False, 'points': 0.5, 'schema_version': 3, 'solution': True}}
# %matplotlib inline
import matplotlib.pyplot as plt
import imageio

im = imageio.imread("imageio:camera.png")

plt.figure()
plt.title(f"shape: {im.shape}")
### BEGIN SOLUTION
print(plt.rcParams['image.cmap'])
plt.gray()
### END SOLUTION
plt.imshow(im)
plt.show()
```

<!-- #region nbgrader={"grade": false, "grade_id": "cell-be882dcd39e9375a", "locked": true, "schema_version": 3, "solution": false} -->
**(c) interpolation:** Demonstrate the effect of the `interpolation=` parameter on a small (e.g. $4\times 4$) image. Discuss in what situations you would use which interpolation technique.
<!-- #endregion -->

<!-- #region nbgrader={"grade": true, "grade_id": "cell-40b940437c4c0ae5", "locked": false, "points": 1, "schema_version": 3, "solution": true} -->

<!-- #endregion -->

```{python}
# %matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

im = np.random.randint(0,16,(4,4))


plt.figure()
plt.title(f"Image: {im.shape}")
plt.imshow(im, interpolation="none")
plt.show()
```

<!-- #region nbgrader={"grade": false, "grade_id": "cell-9f869cf13a972e4d", "locked": true, "schema_version": 3, "solution": false} -->
**(d)** Consider the following example: Two images are created, one with values in the range $[0,128[$, the other with values in the range $[0,256[$. Yet both images appear identical when displayed with `imshow`. Explain this effect and what to do to make the first image appear darker.
<!-- #endregion -->

<!-- #region nbgrader={"grade": true, "grade_id": "cell-ba0b895740412a54", "locked": false, "points": 1, "schema_version": 3, "solution": true} -->
`imshow` automatically adapts the colors used for display to the range of the images value. If you want to avoid this, you have to specify an explicit range via the `vmin` and `vmax` parameters.
<!-- #endregion -->

```{python}
# %matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

im1 = np.arange(0,128).reshape(8,16)
im2 = np.arange(0,256,2).reshape(8,16)

plt.figure(figsize=(12,3))
plt.subplot(1,2,1)
plt.title(f"Image1: {im1.min()}-{im1.max()}")
plt.imshow(im1)
plt.subplot(1,2,2)
plt.title(f"Image1: {im2.min()}-{im2.max()}")
plt.imshow(im2)
plt.show()
```

<!-- #region nbgrader={"grade": false, "grade_id": "cell-3fdf7b0b1dd58f16", "locked": true, "schema_version": 3, "solution": false} -->
**(e)** Explain in your own words the effect of the `extent=` parameter. Create a small example demonstrating the effect.
<!-- #endregion -->

<!-- #region nbgrader={"grade": true, "grade_id": "cell-3da2b447d11b998c", "locked": false, "points": 0.5, "schema_version": 3, "solution": true, "task": false} -->

<!-- #endregion -->

```{python nbgrader={'grade': True, 'grade_id': 'cell-df27e8647a557b96', 'locked': False, 'points': 0.5, 'schema_version': 3, 'solution': True, 'task': False}}
# %matplotlib inline
import matplotlib.pyplot as plt
import imageio

im = imageio.imread("imageio:camera.png")

plt.figure()
plt.title(f"Image: {im.shape}")
### BEGIN SOLUTION
plt.imshow(im, extent=(0,100,0,100))
plt.plot((0,100),(0,100))
### END SOLUTION
plt.show()
```
